config/routes.rb
Rails.application.routes.draw do
  	devise_for :users
    resources :users,only: [:show,:edit,:update,:index] do
      resource :relationships, only: [:create, :destroy]
      get 'follows' => 'relationships#follower', as: 'follows'
      get 'followers' => 'relationships#followed', as: 'followers'
    end
  	resources :books, only: [:index, :show, :edit, :update, :create, :destroy] do
  		resource :favorites, only: [:create, :destroy]
  		resource :book_comments, only: [:create, :destroy]
  	end
	root to: 'homes#top'
	get 'home/about', to: 'homes#about'
  get 'search/search', to: 'search#search'
  # get 'relationship/followed', to: 'relationships#followed'
  # get 'relationship/follower', to: 'relationships#follower'

	# post 'follow/:id', to: 'relationships#follow', as: 'follow'
	# post 'unfollow/:id', to: 'relationships#unfollow', as: 'unfollow'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image, destroy: false

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books
  has_many :book_comments
  has_many :favorites


  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
    # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end


  def already_favorite?(book)
    self.favorites.exists?(book_id: book.id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  def index
  	@users = User.all
  	@user = current_user
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end

  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end


  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.follower.count %></td>
        <td>フォロワー数：<%= user.followed.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
      <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/_list.html.erb
<!-- <div class="col-xs-3">

			<h2>User info</h2>
				<%= attachment_image_tag user, :profile_image, :fill, 100, 100, class:"pull-left profile-thumb", fallback: "no_image.jpg" %>
				<table class="table">
					<tbody>
						<tr></tr>
						<tr>
							<th>name</th>
							<th><%= user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= user.introduction %></th>
						</tr>
						<tr>
							<th>follows</th>
							<th><%= link_to user.follower.count,user_follows_path(user.id) %></th>
						</tr>
						<tr>
							<th>followers</th>
							<th><%= link_to user.followed.count, user_followers_path(user.id) %></th>
						</tr>
					</tbody>
				</table>

			<div class="row">
			<% if user.id == current_user.id %>
				<p class="actions">
					<%= link_to "", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
				</p>
				<% else %>
					<p class="actions">
						<% unless user == current_user %>
						<% if current_user.following?(user) %>
	        				<%= link_to "フォロー外す", user_relationships_path(user.id), method: :DELETE, class:"btn btn-primary" %>
	      					<% else %>
	        				<%= link_to "フォローする", user_relationships_path(user.id), method: :POST, class:"btn btn-info" %>
	      				<% end %>
	      				<% end %>
	      			</p>
			<% end %>
			</div>

			<h2>New book</h2>

			<%= form_for(Book.new) do |f| %>
				<div class="field row">
					<p class="new-book-title">
					<%= f.label :title %><br>
					<%= f.text_field :title, class:"col-xs-12" %>
				    </p>
				    <p class="new-book-body">
					<%= f.label :opinion %><br>
					<%= f.text_area :body, class:"col-xs-12" %>
				    </p>
					<p class="actions">
					<%= f.submit 'Create Book', class:"col-xs-12 btn btn-primary" %>
					</p>
				</div>
			<% end %>
	</div>
 -->

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_for(@user) do |f| %>
    <%= render 'layouts/errors', obj: @user %>

	<p class="field">
		<%= f.label :name %>
    	<%= f.text_field :name %>
    </p>
	<p class="field">
        <label class="control-label sr-only" for="inputEmail">image</label>
        <%= f.attachment_field :profile_image, class:"user-edit-form" %>
    </p>
    <p class="field">
    	<%= f.label :introduction %>
    	<%= f.text_area :introduction %>
    </p>
    <p class="actions">
    	<%= f.submit "Update User", class:"btn btn-base-1 mt-20　border" %>
	</p>
<% end %>

app/views/users/index.html.erb
<div class="row">

	<div class='col-xs-3'>
    	<h2>User info</h2>
    	<%= render 'info', user: current_user %>

    	<h2>New book</h2>
    	<%= render 'books/form', book: @book %>

  	</div>

  	<div class='col-xs-9'>
    	<h2>Users</h2>
		<%= render 'index',users: @users %>
  	</div>

</div>

app/views/users/show.html.erb
<div class='row'>

  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: @user,now: ''%>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'books/index',books: @books %>
  </div>
</div>